{% set name = "yahoo-search-py" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/yahoo-search-py-{{ version }}.tar.gz
  sha256: 01b5ca2ff117e9e3aca3754c233e49272793cb013de7652f70be48bcddb31772

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=62.6,<66
    - setuptools-scm >=6.2,<8
    - pip
  run:
    - python >={{ python_min }},<3.12
    - httpx
    - pydantic
    - selectolax
    - urllib3

test:
  imports:
    - yahoo_search
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: 'Search anything on Yahoo: web pages, news, videos, autocomplete, and weather.'
  home: https://github.com/AWeirdDev/yahoo-search
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
